/**
 * Report export helpers for the AI Report Summary (Daily/Weekly/Monthly).
 * "Copy Summary" builds plain text for the clipboard; the PDF export lazy-
 * loads jsPDF only when actually requested — same pattern already used by
 * lib/exportUtils.js and lib/printer/templates/receiptPdf.ts.
 */

export function buildSummaryText(report) {
  const lines = [];
  lines.push(`${report.title} — ${report.restaurantName}`);
  lines.push(`${report.rangeLabel} · Generated ${new Date(report.generatedAt).toLocaleString("en-IN")}`);
  lines.push("");
  report.narrative.forEach((line) => lines.push(`• ${line}`));

  if (report.topSellers?.length > 0) {
    lines.push("");
    lines.push("Top Sellers:");
    report.topSellers.forEach((s, i) => lines.push(`${i + 1}. ${s.name} — ${s.quantity} sold, ₹${s.revenue.toLocaleString("en-IN")}`));
  }

  if (report.recommendations?.length > 0) {
    lines.push("");
    lines.push("Suggestions:");
    report.recommendations.forEach((r) => lines.push(`- ${r.text}`));
  }

  return lines.join("\n");
}

export async function copySummaryToClipboard(report) {
  const text = buildSummaryText(report);
  await navigator.clipboard.writeText(text);
}

export async function downloadReportPDF(report) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  let y = 22;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(61, 39, 16);
  doc.text(report.title, margin, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(120, 100, 80);
  doc.text(`${report.restaurantName} · ${report.rangeLabel}`, margin, y);
  y += 5;
  doc.text(`Generated ${new Date(report.generatedAt).toLocaleString("en-IN")}`, margin, y);
  y += 10;

  doc.setDrawColor(232, 137, 28);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(61, 39, 16);
  doc.text("Summary", margin, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  doc.setTextColor(40, 30, 20);
  report.narrative.forEach((line) => {
    const wrapped = doc.splitTextToSize(`• ${line}`, pageWidth - margin * 2);
    doc.text(wrapped, margin, y);
    y += wrapped.length * 5.5;
  });
  y += 4;

  if (report.topSellers?.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(61, 39, 16);
    doc.text("Top Sellers", margin, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(40, 30, 20);
    report.topSellers.forEach((s, i) => {
      doc.text(`${i + 1}. ${s.name} — ${s.quantity} sold, Rs.${s.revenue.toLocaleString("en-IN")}`, margin, y);
      y += 6;
    });
    y += 4;
  }

  if (report.recommendations?.length > 0) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(61, 39, 16);
    doc.text("Suggestions", margin, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(40, 30, 20);
    report.recommendations.forEach((r) => {
      const wrapped = doc.splitTextToSize(`- ${r.text}`, pageWidth - margin * 2);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 5.5;
    });
  }

  doc.setFontSize(8.5);
  doc.setTextColor(160, 140, 120);
  doc.text("Generated by ServeSync AI Copilot — computed from your restaurant's own data.", margin, doc.internal.pageSize.getHeight() - 12);

  doc.save(`${report.period}-ai-report.pdf`);
}
